name: Publish App

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: windows-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: compile-sass
        run: |
          yarn sass-compiler --compile
      - name: compile typescript
        run: |
          yarn tsc
      - name: Publish
        run: |
          yarn run publish
          dir
        env:
          GITHUB_TOKEN: ${{ github.token }}